server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/xml,text/xml,image/svg+xml

spring:
  application:
    name: promonasos-web
  thymeleaf:
    cache: false

# Аналог секции "Sait" из appsettings.json оригинала.
sait:
  nazvanie: 'ТД «Промоборудование»'
  domen: https://hermetica.su
  telefon: '+7 (495) 925-05-03'
  telefon-ssylka: '+74959250503'
  pochta: info@hermetica.su
  adres: '109544, г. Москва, ул. Рабочая, д. 93, стр. 2, офис 236'
  grafik-raboty: 'пн–пт 9:00–18:00'
  god-osnovaniya: '2001'
